"""initial

Revision ID: bda413a2dfdd
Revises: 
Create Date: 2026-04-29 16:38:16.673112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda413a2dfdd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_timestamp', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_table('early_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_early_subscribers_email'), 'early_subscribers', ['email'], unique=True)
    op.create_index('ix_es_deleted', 'early_subscribers', ['deleted_at'], unique=False)
    op.create_index('ix_es_email', 'early_subscribers', ['email'], unique=False)
    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_email', sa.String(length=255), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_ic_deleted', 'invite_codes', ['deleted_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('subscription_type', sa.Enum('free', 'premium', name='subscription_type_enum'), nullable=False),
    sa.Column('subscription_end', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_deleted', 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=False)
    op.create_table('ai_token_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_token_usage_model'), 'ai_token_usage', ['model'], unique=False)
    op.create_index(op.f('ix_ai_token_usage_user_id'), 'ai_token_usage', ['user_id'], unique=False)
    op.create_index('ix_token_created', 'ai_token_usage', ['created_at'], unique=False)
    op.create_index('ix_token_model', 'ai_token_usage', ['model'], unique=False)
    op.create_index('ix_token_user', 'ai_token_usage', ['user_id'], unique=False)
    op.create_index('ix_token_user_created', 'ai_token_usage', ['user_id', 'created_at'], unique=False)
    op.create_table('electional_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('computing', 'done', 'error', name='electional_status_enum'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('request_data', sa.JSON(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_el_user', 'electional_cache', ['user_id'], unique=False)
    op.create_index('ix_el_user_hash', 'electional_cache', ['user_id', 'input_hash'], unique=True)
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('datetime', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_person_user', 'persons', ['user_id'], unique=False)
    op.create_table('rectification_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('computing', 'done', 'error', name='rectification_status_enum'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('request_data', sa.JSON(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rect_user', 'rectification_cache', ['user_id'], unique=False)
    op.create_index('ix_rect_user_hash', 'rectification_cache', ['user_id', 'input_hash'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_rt_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('ix_rt_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('monthly', 'quarterly', 'yearly', name='subscription_plan_enum'), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'expired', 'pending', 'failed', name='subscription_status_enum'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subs_deleted', 'subscriptions', ['deleted_at'], unique=False)
    op.create_index('ix_subs_user', 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_subs_user_status', 'subscriptions', ['user_id', 'status'], unique=False)
    op.create_table('charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('chart_type', sa.Enum('natal', 'synastry', 'transit', 'solar_return', 'lunar_return', 'profection', 'solar_arc', 'progression', 'composite', 'davison', 'horary', 'electional', 'planetary_return', name='chart_type_enum'), nullable=False),
    sa.Column('parent_chart_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('native_data', sa.JSON(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('svg_data', sa.Text(), nullable=True),
    sa.Column('svg_path', sa.String(length=500), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_chart_id'], ['charts.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chart_deleted', 'charts', ['deleted_at'], unique=False)
    op.create_index('ix_chart_parent', 'charts', ['parent_chart_id'], unique=False)
    op.create_index('ix_chart_type', 'charts', ['chart_type'], unique=False)
    op.create_index('ix_chart_user', 'charts', ['user_id'], unique=False)
    op.create_index('ix_chart_user_created', 'charts', ['user_id', 'created_at'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('stripe_payment_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'succeeded', 'failed', 'refunded', 'cancelled', name='payment_status_enum'), nullable=False),
    sa.Column('payment_method', sa.Enum('card', 'bank_transfer', 'paypal', name='payment_method_enum'), nullable=False),
    sa.Column('failure_message', sa.String(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pay_deleted', 'payments', ['deleted_at'], unique=False)
    op.create_index('ix_pay_stripe', 'payments', ['stripe_payment_id'], unique=False)
    op.create_index('ix_pay_sub', 'payments', ['subscription_id'], unique=False)
    op.create_index('ix_pay_user', 'payments', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cs_chart', 'chat_sessions', ['chart_id'], unique=False)
    op.create_index('ix_cs_deleted', 'chat_sessions', ['deleted_at'], unique=False)
    op.create_index('ix_cs_user', 'chat_sessions', ['user_id'], unique=False)
    op.create_index('ix_cs_user_chart', 'chat_sessions', ['user_id', 'chart_id'], unique=False)
    op.create_table('insight_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('natal_chart_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.Enum('astro_twins', 'historical_parallels', name='insight_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('computing', 'done', 'error', name='insight_status_enum'), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['natal_chart_id'], ['charts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insight_natal_type', 'insight_cache', ['natal_chart_id', 'insight_type'], unique=True)
    op.create_table('planner_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('preset', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('computing', 'done', 'error', name='planner_status_enum'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('request_data', sa.LargeBinary(), nullable=False),
    sa.Column('pdf_data', sa.LargeBinary(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pl_user', 'planner_cache', ['user_id'], unique=False)
    op.create_index('ix_pl_user_hash', 'planner_cache', ['user_id', 'input_hash'], unique=True)
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_request_logs_chart', 'request_logs', ['chart_id'], unique=False)
    op.create_index('ix_request_logs_endpoint', 'request_logs', ['endpoint'], unique=False)
    op.create_index('ix_request_logs_timestamp', 'request_logs', ['created_at'], unique=False)
    op.create_index('ix_request_logs_user', 'request_logs', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cm_session', 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cm_session', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_request_logs_user', table_name='request_logs')
    op.drop_index('ix_request_logs_timestamp', table_name='request_logs')
    op.drop_index('ix_request_logs_endpoint', table_name='request_logs')
    op.drop_index('ix_request_logs_chart', table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index('ix_pl_user_hash', table_name='planner_cache')
    op.drop_index('ix_pl_user', table_name='planner_cache')
    op.drop_table('planner_cache')
    op.drop_index('ix_insight_natal_type', table_name='insight_cache')
    op.drop_table('insight_cache')
    op.drop_index('ix_cs_user_chart', table_name='chat_sessions')
    op.drop_index('ix_cs_user', table_name='chat_sessions')
    op.drop_index('ix_cs_deleted', table_name='chat_sessions')
    op.drop_index('ix_cs_chart', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('ix_pay_user', table_name='payments')
    op.drop_index('ix_pay_sub', table_name='payments')
    op.drop_index('ix_pay_stripe', table_name='payments')
    op.drop_index('ix_pay_deleted', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_chart_user_created', table_name='charts')
    op.drop_index('ix_chart_user', table_name='charts')
    op.drop_index('ix_chart_type', table_name='charts')
    op.drop_index('ix_chart_parent', table_name='charts')
    op.drop_index('ix_chart_deleted', table_name='charts')
    op.drop_table('charts')
    op.drop_index('ix_subs_user_status', table_name='subscriptions')
    op.drop_index('ix_subs_user', table_name='subscriptions')
    op.drop_index('ix_subs_deleted', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_rt_user', table_name='refresh_tokens')
    op.drop_index('ix_rt_hash', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_rect_user_hash', table_name='rectification_cache')
    op.drop_index('ix_rect_user', table_name='rectification_cache')
    op.drop_table('rectification_cache')
    op.drop_index('ix_person_user', table_name='persons')
    op.drop_table('persons')
    op.drop_index('ix_el_user_hash', table_name='electional_cache')
    op.drop_index('ix_el_user', table_name='electional_cache')
    op.drop_table('electional_cache')
    op.drop_index('ix_token_user_created', table_name='ai_token_usage')
    op.drop_index('ix_token_user', table_name='ai_token_usage')
    op.drop_index('ix_token_model', table_name='ai_token_usage')
    op.drop_index('ix_token_created', table_name='ai_token_usage')
    op.drop_index(op.f('ix_ai_token_usage_user_id'), table_name='ai_token_usage')
    op.drop_index(op.f('ix_ai_token_usage_model'), table_name='ai_token_usage')
    op.drop_table('ai_token_usage')
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_index('ix_users_deleted', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_ic_deleted', table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index('ix_es_email', table_name='early_subscribers')
    op.drop_index('ix_es_deleted', table_name='early_subscribers')
    op.drop_index(op.f('ix_early_subscribers_email'), table_name='early_subscribers')
    op.drop_table('early_subscribers')
    op.drop_index('ix_audit_user_action', table_name='audit_logs')
    op.drop_index('ix_audit_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    # ### end Alembic commands ###